---
# Syncthing handlers

- name: restart syncthing
  ansible.builtin.systemd:
    name: "syncthing-{{ syncthing_user if syncthing_service_type == 'system' else '@' + syncthing_user }}"
    state: restarted
    scope: system
  become: true
  when: ansible_service_mgr == "systemd"
