# This file defines the default variables for the base role in an Ansible playbook.

required_packages:
  - sudo
  - git
dotfiles_repo: "https://github.com/jcnichols22/dotfiles.git"
#dotfiles_repo: "git@github.com:jcnichols22/Ansible.git"

